default: &default
    adapter: postgresql
    encoding: unicode

development:
    <<: *default
    database: landlord_development

test:
    <<: *default
    database: landlord_test

production:
    <<: *default
    database: landlord_production
    username: landlord
    password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
  